#!groovy

/**
 *	Copyright (c) 2017 SAP SE or an SAP affiliate company.  All rights reserved.
 *
 *	This software is the confidential and proprietary information of SAP
 *	("Confidential Information"). You shall not disclose such Confidential
 *	Information and shall use it only in accordance with the terms of the
 *	license agreement you entered into with SAP.
*/

@Library('piper-library-os') _

node('master') {

  APP_PATH = 'src'
  SRC = "${WORKSPACE}/${APP_PATH}"

  def cmEndpoint = 'https://fbt.wdf.sap.corp:44300/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV/'
  def cmCredentialsId = 'CM_CLIENT'

  def changeId
  def isChangeInDevelopment
  def mtaFilePath
  def transportRequestId

  stage("Clone sources and setup environment"){
    deleteDir()
    dir(APP_PATH) {
      checkout scm
      setupCommonPipelineEnvironment script: this
    }
  }

  stage("Get Change Document"){
    changeId = '8000038673'
  }

  stage("Verify Change Document"){

    echo "[INFO] Verifying change document '$changeId'."
	
    withCredentials([usernamePassword(credentialsId: cmCredentialsId, passwordVariable: 'cmPassword', usernameVariable: 'cmUsername')]) {
        isChangeInDevelopment = shStatus "cmclient \
            -e $cmEndpoint \
            -u $cmUsername \
            -p $cmPassword \
			-t SOLMAN \
		    is-change-in-development -cID '$changeId' --return-code"
    }

	if (isChangeInDevelopment) echo "[INFO] Change document '$changeId' is in development."
	else error "Change document '$changeId' is not in development."
  }

  stage("Build Fiori App"){
    dir(SRC){
      mtaFilePath = mtaBuild script: this, buildTarget: 'NEO'
    }
  }

  stage("Deploy Fiori App"){
    dir(SRC){
      neoDeploy script: this, archivePath: mtaFilePath
    }
  }

  stage("Get open Transport Request"){

    echo "[INFO] Getting transport request for change '$changeId'."

    def transportRequests
    withCredentials([usernamePassword(credentialsId: cmCredentialsId, passwordVariable: 'cmPassword', usernameVariable: 'cmUsername')]) {
        transportRequests = shOutput "cmclient \
            -e $cmEndpoint \
            -u $cmUsername \
            -p $cmPassword \
			-t SOLMAN \
          get-transports --modifiable-only -cID $changeId" 
		transportRequests = transportRequests.split("\n")
    }
    if(transportRequests.length>1){
        error "Too many open Transport Requests in Change Document $changeId. Transport Requests found: ${transportRequests.join(', ')}"
    }
	else if(!transportRequests || transportRequests.length == 0 || (transportRequests.length == 1 && !transportRequests[0])){

	  	echo "[INFO] There is no open transport request for change document '$changeId'."
      
	    echo "[INFO] Creating transport request for change document '$changeId'."
	    
        withCredentials([usernamePassword(credentialsId: cmCredentialsId, passwordVariable: 'cmPassword', usernameVariable: 'cmUsername')]) {
	      try {
            transportRequestId = shOutput "cmclient \
                -e $cmEndpoint \
                -u $cmUsername \
                -p $cmPassword \
	    		 -t SOLMAN \
	    	    create-transport -cID '$changeId' -dID 'L21~EXT_SRV'"
          } catch(Exception e) {
            error "Cannot create a transport request for change id '$changeId'. $e.message."
          }
        }
      
	    echo "[INFO] The transport request '$transportRequestId' for change document '$changeId' has been successfully created."
    }
	else {
	    transportRequestId = transportRequests[0]
        echo "[INFO] Transport Request '$transportRequestId' available for Change Document '$changeId'."
	}
  }

  stage("Upload Fiori App to Transport Request") {
    dir(SRC){
	 
	  echo "[INFO] Uploading mta file '$mtaFilePath' to transport request '$transportRequestId' of change document '$changeId'."
	 
	  withCredentials([usernamePassword(credentialsId: cmCredentialsId, passwordVariable: 'cmPassword', usernameVariable: 'cmUsername')]) {
        success = shStatus "cmclient \
            -e $cmEndpoint \
            -u $cmUsername \
            -p $cmPassword \
			-t SOLMAN \
            upload-file-to-transport -cID '$changeId' -tID '$transportRequestId' 'HCP' '$mtaFilePath'"
      }

      if (success) echo "[INFO] Fiori App '$mtaFilePath' successfully uploaded to transport request '$transportRequestId' of change document '$changeId'."
	  else error "Fiori App '$mtaFilePath' could not be uploaded to transport request '$transportRequestId' of change document '$changeId'."
    }
  }
}

String shOutput(String command) {
    result = sh returnStdout: true, script: command
    return result.trim()
}

Boolean shStatus(String command) {
    result = sh returnStatus: true, script: command
    return result == 0
}